version: "3.7"  

volumes:
  db:

services:
  &mysql test-name-mysql:
    container_name: *mysql
    hostname: *mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: &MYSQL_ROOT_PASS examplepass5
    volumes:
      - db:/var/lib/mysql
    networks:
      - web
  &php74-fpm test-php-fpm:
    container_name: *php74-fpm
    hostname: *php74-fpm
    command: php-fpm
    environment:
      FPM_PORT: &PHP74_PORT 9000
      FPM_USER: "${CURRENT_USER_ID}"
      FPM_GROUP: "${CURRENT_USER_ID}"
      CURRENT_USER: "${CURRENT_USER}"
      SCHEDULE_PERIOD: 60
    restart: always
    build:
      ./docker/php
    volumes:
      - ./code:/var/www/html/:rw
    networks:
      - web
  &httpd test-httpd:
    container_name: *httpd
    hostname: *httpd
    environment:
      PHP74_HOST: *php74-fpm
      PHP74_PORT: *PHP74_PORT
    volumes:
      - ./code:/var/www/html/
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    build: 
      ./docker/apache
    ports:
      - ${APACHE_CONTAINER_PORT}:80
    restart: always
    depends_on:
      - *mysql
    networks:
      - web    
  &pma-service test-name-phpmyadmin:
    container_name: *pma-service
    hostname: *pma-service
    restart: always
    depends_on:
      - *mysql
    image: phpmyadmin
    environment:
      PMA_HOST: *mysql
      MYSQL_ROOT_PASSWORD: *MYSQL_ROOT_PASS
      UPLOAD_LIMIT: "1G"
    ports:
      - ${PHPMYADMIN_CONTAINER_PORT}:80
    networks:
      - web
  &node-service test-name-node:
    container_name: *node-service
    hostname: *node-service
    restart: on-failure
    user: "1000:1000"
    build:
      ./docker/node
    working_dir: /var/www/html
    volumes:
      - ./code:/var/www/html/:rw
networks:
  web: 
  
   
      
